# config.yaml
envs:
  bdiv_env:
    source activate ete2
  qiime_env:
    source activate qiime
  codiv_env:
    source activate qiime
  codiv_scripts_dir:
    /home/jgsanders/git_sw/codiversification
bdiv_params:
  bdiv_metrics:
    - binary_jaccard
    - unweighted_unifrac
    - weighted_unifrac
  bdiv_OTU_widths:
    - 85
    - 88
    - 91
    - 94
    - 97
    - 99
  color_by:
    - Species_tree
    - Diet
    - Phyl_Group
  jk_permutations:
    100
  jk_depth:
    7200
codiv_params:
  annotate_trees:
    - bh_FDR_sig_nodes
    - bonferroni_sig_nodes
  otu_picking_method:
    usearch61
  pOTU_widths:
    - 91
    - 94
    - 97
    - 99
  collapse_field:
    Species_tree
  pOTU_rarify:
    10000
  min_obvs:
    3
  pOTU_chunks:
    8
  codiv_test:
    hommola_host
  permutations:
    10000
input_files:
  annotate_host_tree_fp:
    /home/ssong/sanders_anal/deblurred_redo/input_files/monkey_subtree.tre
  codiv_host_tree_fp:
    /home/ssong/sanders_anal/deblurred_redo/input_files/primate_tree_376_taxa-chronogram_newick.tre
  bdiv_host_tree_fp:
    /home/ssong/sanders_anal/deblurred_redo/input_files/furcated_host_tree.tre
  deblurred_biom:
    /home/ssong/sanders_anal/deblurred_redo/input_files/final.withtax.min10.biom
  sample_map:
    /home/ssong/sanders_anal/deblurred_redo/input_files/Reduced_mapping_4persp_nohyb_RC2036.txt
  chimera_ref:
    /home/jgsanders/ref_data/gg_13_8_otus/rep_set/97_otus.fasta
  cOTU_params_fp:
    /home/jgsanders/git_sw/codiversification/params/100_fasttree_muscle_sumaclust_params.txt


